
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-14
owner: ucsb-cs156-f25
repo_name: team01-f25-14
pull_requests: [{"author":{"id":"U_kgDOCvCqLg","is_bot":false,"login":"PratimaNallapareddy","name":"Pratima R Nallapareddy"},"headRefName":"pn-organizations-get-by-id","number":60,"title":"Pn - add GET by id for organizations","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/60"},{"author":{"id":"U_kgDOCVHRvw","is_bot":false,"login":"logan-melgoza","name":"Logan Melgoza"},"headRefName":"lm-MenuItemReview-add-delete","number":59,"title":"lm - added DELETE for MenuItemReviewC","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/59"},{"author":{"id":"U_kgDOCVHRvw","is_bot":false,"login":"logan-melgoza","name":"Logan Melgoza"},"headRefName":"lm-MenuItemReview-add-put","number":58,"title":"lm - added PUT for MenuItemReview","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/58"},{"author":{"id":"U_kgDOCvCqLg","is_bot":false,"login":"PratimaNallapareddy","name":"Pratima R Nallapareddy"},"headRefName":"pn-create-UCSBOrganization-controller","number":56,"title":"Pn- create UCSBOrganization controller, add GET /all and POST methods","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/56"},{"author":{"id":"U_kgDOCIZ8Xg","is_bot":false,"login":"Fern4ndo99","name":""},"headRefName":"fvelazquez/HelpRequestController-PUT","number":55,"title":"fv - Add PUT (edit) endpoint for a single record in HelpRequest table","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/55"},{"author":{"id":"U_kgDOCIZ8Xg","is_bot":false,"login":"Fern4ndo99","name":""},"headRefName":"fvelazquez/HelpRequestController-DELETE","number":54,"title":"fv - Add DELETE endpoint for a specific record in HelpRequest table","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/54"},{"author":{"id":"U_kgDOCIZ8Xg","is_bot":false,"login":"Fern4ndo99","name":""},"headRefName":"fvelazquez/HelpRequestController-GET","number":53,"title":"fv - Add GET (show) endpoint for a single HelpRequest record","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/53"},{"author":{"id":"U_kgDOCvCqLg","is_bot":false,"login":"PratimaNallapareddy","name":"Pratima R Nallapareddy"},"headRefName":"pratima-UCSBOrganization-create-db","number":51,"title":"pc - create database file for UCSBOrganization","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/51"},{"author":{"id":"U_kgDOCujG6A","is_bot":false,"login":"danielc-285","name":""},"headRefName":"Daniel-DiningMenuDELETE","number":47,"title":"Add DELETE function for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/47"}]
