
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-14
owner: ucsb-cs156-f25
repo_name: team01-f25-14
pull_requests: [{"author":{"id":"U_kgDOCM73Qg","is_bot":false,"login":"KeyiZong27","name":"KEYI ZONG"},"headRefName":"kz-Articles-create-delete","number":73,"title":"Kz articles create delete","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/73"},{"author":{"id":"U_kgDOCM73Qg","is_bot":false,"login":"KeyiZong27","name":"KEYI ZONG"},"headRefName":"kz-Articles-create-get","number":72,"title":"Kz articles create get","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/72"},{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"Catherine-delete","number":71,"title":"Catherine delete","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/71"},{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"Catherine-push","number":70,"title":"Catherine put","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/70"},{"author":{"id":"U_kgDOCM73Qg","is_bot":false,"login":"KeyiZong27","name":"KEYI ZONG"},"headRefName":"kz-Articles-create-put","number":69,"title":"kz - added PUT to Articles","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/69"},{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"Catherine-GetID","number":68,"title":"Catherine - added get by id on controller","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/68"},{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"Catherine-RecRequestController","number":64,"title":"Catherine rec request controller","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/64"},{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"Catherine-RecRequestTable","number":62,"title":"added recommendation request database","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/62"}]
