
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-14
owner: ucsb-cs156-f25
repo_name: team01-f25-14
pull_requests: [{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"Catherine-GetID","number":68,"title":"Catherine - added get by id on controller","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/68"},{"author":{"id":"U_kgDOCvCqLg","is_bot":false,"login":"PratimaNallapareddy","name":"Pratima R Nallapareddy"},"headRefName":"pn-delete-for-organization-table","number":65,"title":"Pn delete for organization table","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/65"},{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"Catherine-RecRequestController","number":64,"title":"Catherine rec request controller","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/64"},{"author":{"id":"U_kgDOCvCqLg","is_bot":false,"login":"PratimaNallapareddy","name":"Pratima R Nallapareddy"},"headRefName":"pn-put-for-commit-table","number":63,"title":"Pn-put for commit table","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/63"},{"author":{"id":"U_kgDOCOTuMA","is_bot":false,"login":"cthrnzhong","name":""},"headRefName":"Catherine-RecRequestTable","number":62,"title":"added recommendation request database","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/62"},{"author":{"id":"U_kgDOCvCqLg","is_bot":false,"login":"PratimaNallapareddy","name":"Pratima R Nallapareddy"},"headRefName":"pn-organizations-get-by-id","number":60,"title":"Pn - add GET by id for organizations","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/60"},{"author":{"id":"U_kgDOCvCqLg","is_bot":false,"login":"PratimaNallapareddy","name":"Pratima R Nallapareddy"},"headRefName":"pn-create-UCSBOrganization-controller","number":56,"title":"Pn- create UCSBOrganization controller, add GET /all and POST methods","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/56"},{"author":{"id":"U_kgDOCvCqLg","is_bot":false,"login":"PratimaNallapareddy","name":"Pratima R Nallapareddy"},"headRefName":"pratima-UCSBOrganization-create-db","number":51,"title":"pc - create database file for UCSBOrganization","url":"https://github.com/ucsb-cs156-f25/team01-f25-14/pull/51"}]
